// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: MutableNotificationService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_mutable_notification_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services MutableNotificationService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	repositories "github.com/fromsi/jwt-oauth-sso/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockMutableNotificationService is a mock of MutableNotificationService interface.
type MockMutableNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockMutableNotificationServiceMockRecorder
	isgomock struct{}
}

// MockMutableNotificationServiceMockRecorder is the mock recorder for MockMutableNotificationService.
type MockMutableNotificationServiceMockRecorder struct {
	mock *MockMutableNotificationService
}

// NewMockMutableNotificationService creates a new mock instance.
func NewMockMutableNotificationService(ctrl *gomock.Controller) *MockMutableNotificationService {
	mock := &MockMutableNotificationService{ctrl: ctrl}
	mock.recorder = &MockMutableNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableNotificationService) EXPECT() *MockMutableNotificationServiceMockRecorder {
	return m.recorder
}

// SendTextByUser mocks base method.
func (m *MockMutableNotificationService) SendTextByUser(arg0 repositories.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTextByUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTextByUser indicates an expected call of SendTextByUser.
func (mr *MockMutableNotificationServiceMockRecorder) SendTextByUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTextByUser", reflect.TypeOf((*MockMutableNotificationService)(nil).SendTextByUser), arg0, arg1)
}
