// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: MutableUserService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_mutable_user.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services MutableUserService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMutableUserService is a mock of MutableUserService interface.
type MockMutableUserService struct {
	ctrl     *gomock.Controller
	recorder *MockMutableUserServiceMockRecorder
	isgomock struct{}
}

// MockMutableUserServiceMockRecorder is the mock recorder for MockMutableUserService.
type MockMutableUserServiceMockRecorder struct {
	mock *MockMutableUserService
}

// NewMockMutableUserService creates a new mock instance.
func NewMockMutableUserService(ctrl *gomock.Controller) *MockMutableUserService {
	mock := &MockMutableUserService{ctrl: ctrl}
	mock.recorder = &MockMutableUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableUserService) EXPECT() *MockMutableUserServiceMockRecorder {
	return m.recorder
}

// CreateUserByUUIDAndEmailAndHashedPassword mocks base method.
func (m *MockMutableUserService) CreateUserByUUIDAndEmailAndHashedPassword(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserByUUIDAndEmailAndHashedPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserByUUIDAndEmailAndHashedPassword indicates an expected call of CreateUserByUUIDAndEmailAndHashedPassword.
func (mr *MockMutableUserServiceMockRecorder) CreateUserByUUIDAndEmailAndHashedPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserByUUIDAndEmailAndHashedPassword", reflect.TypeOf((*MockMutableUserService)(nil).CreateUserByUUIDAndEmailAndHashedPassword), arg0, arg1, arg2)
}

// UpdatePasswordByUUIDAndHashedPassword mocks base method.
func (m *MockMutableUserService) UpdatePasswordByUUIDAndHashedPassword(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByUUIDAndHashedPassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordByUUIDAndHashedPassword indicates an expected call of UpdatePasswordByUUIDAndHashedPassword.
func (mr *MockMutableUserServiceMockRecorder) UpdatePasswordByUUIDAndHashedPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByUUIDAndHashedPassword", reflect.TypeOf((*MockMutableUserService)(nil).UpdatePasswordByUUIDAndHashedPassword), arg0, arg1)
}
