// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: NotificationService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_notification_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services NotificationService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	repositories "github.com/fromsi/jwt-oauth-sso/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// SendTextByUser mocks base method.
func (m *MockNotificationService) SendTextByUser(arg0 repositories.User, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTextByUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTextByUser indicates an expected call of SendTextByUser.
func (mr *MockNotificationServiceMockRecorder) SendTextByUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTextByUser", reflect.TypeOf((*MockNotificationService)(nil).SendTextByUser), arg0, arg1)
}
