// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: ResetTokenService)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/services/mock_reset_token_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services ResetTokenService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	repositories "github.com/fromsi/jwt-oauth-sso/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockResetTokenService is a mock of ResetTokenService interface.
type MockResetTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockResetTokenServiceMockRecorder
	isgomock struct{}
}

// MockResetTokenServiceMockRecorder is the mock recorder for MockResetTokenService.
type MockResetTokenServiceMockRecorder struct {
	mock *MockResetTokenService
}

// NewMockResetTokenService creates a new mock instance.
func NewMockResetTokenService(ctrl *gomock.Controller) *MockResetTokenService {
	mock := &MockResetTokenService{ctrl: ctrl}
	mock.recorder = &MockResetTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetTokenService) EXPECT() *MockResetTokenServiceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockResetTokenService) GenerateToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockResetTokenServiceMockRecorder) GenerateToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockResetTokenService)(nil).GenerateToken))
}

// SendNewResetTokenByUser mocks base method.
func (m *MockResetTokenService) SendNewResetTokenByUser(arg0 repositories.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNewResetTokenByUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNewResetTokenByUser indicates an expected call of SendNewResetTokenByUser.
func (mr *MockResetTokenServiceMockRecorder) SendNewResetTokenByUser(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNewResetTokenByUser", reflect.TypeOf((*MockResetTokenService)(nil).SendNewResetTokenByUser), arg0)
}
