// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: PasswordResetWithTokenRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_password_reset_with_token_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests PasswordResetWithTokenRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetWithTokenRequestBody is a mock of PasswordResetWithTokenRequestBody interface.
type MockPasswordResetWithTokenRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetWithTokenRequestBodyMockRecorder
	isgomock struct{}
}

// MockPasswordResetWithTokenRequestBodyMockRecorder is the mock recorder for MockPasswordResetWithTokenRequestBody.
type MockPasswordResetWithTokenRequestBodyMockRecorder struct {
	mock *MockPasswordResetWithTokenRequestBody
}

// NewMockPasswordResetWithTokenRequestBody creates a new mock instance.
func NewMockPasswordResetWithTokenRequestBody(ctrl *gomock.Controller) *MockPasswordResetWithTokenRequestBody {
	mock := &MockPasswordResetWithTokenRequestBody{ctrl: ctrl}
	mock.recorder = &MockPasswordResetWithTokenRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetWithTokenRequestBody) EXPECT() *MockPasswordResetWithTokenRequestBodyMockRecorder {
	return m.recorder
}

// GetNewPassword mocks base method.
func (m *MockPasswordResetWithTokenRequestBody) GetNewPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetNewPassword indicates an expected call of GetNewPassword.
func (mr *MockPasswordResetWithTokenRequestBodyMockRecorder) GetNewPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewPassword", reflect.TypeOf((*MockPasswordResetWithTokenRequestBody)(nil).GetNewPassword))
}

// GetToken mocks base method.
func (m *MockPasswordResetWithTokenRequestBody) GetToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetToken indicates an expected call of GetToken.
func (mr *MockPasswordResetWithTokenRequestBodyMockRecorder) GetToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockPasswordResetWithTokenRequestBody)(nil).GetToken))
}

// Make mocks base method.
func (m *MockPasswordResetWithTokenRequestBody) Make(arg0 *gin.Context) (requests.PasswordResetWithTokenRequestBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.PasswordResetWithTokenRequestBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockPasswordResetWithTokenRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockPasswordResetWithTokenRequestBody)(nil).Make), arg0)
}
