// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LogoutAllRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_logout_all_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LogoutAllRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutAllRequestBody is a mock of LogoutAllRequestBody interface.
type MockLogoutAllRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutAllRequestBodyMockRecorder
	isgomock struct{}
}

// MockLogoutAllRequestBodyMockRecorder is the mock recorder for MockLogoutAllRequestBody.
type MockLogoutAllRequestBodyMockRecorder struct {
	mock *MockLogoutAllRequestBody
}

// NewMockLogoutAllRequestBody creates a new mock instance.
func NewMockLogoutAllRequestBody(ctrl *gomock.Controller) *MockLogoutAllRequestBody {
	mock := &MockLogoutAllRequestBody{ctrl: ctrl}
	mock.recorder = &MockLogoutAllRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutAllRequestBody) EXPECT() *MockLogoutAllRequestBodyMockRecorder {
	return m.recorder
}

// Make mocks base method.
func (m *MockLogoutAllRequestBody) Make(arg0 *gin.Context) requests.LogoutAllRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LogoutAllRequestBody)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockLogoutAllRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLogoutAllRequestBody)(nil).Make), arg0)
}
