// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: DevicesRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_devices_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests DevicesRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockDevicesRequest is a mock of DevicesRequest interface.
type MockDevicesRequest struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesRequestMockRecorder
	isgomock struct{}
}

// MockDevicesRequestMockRecorder is the mock recorder for MockDevicesRequest.
type MockDevicesRequestMockRecorder struct {
	mock *MockDevicesRequest
}

// NewMockDevicesRequest creates a new mock instance.
func NewMockDevicesRequest(ctrl *gomock.Controller) *MockDevicesRequest {
	mock := &MockDevicesRequest{ctrl: ctrl}
	mock.recorder = &MockDevicesRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesRequest) EXPECT() *MockDevicesRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockDevicesRequest) GetBody() requests.DevicesRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.DevicesRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockDevicesRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockDevicesRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockDevicesRequest) Make(arg0 *gin.Context) requests.DevicesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.DevicesRequest)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockDevicesRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockDevicesRequest)(nil).Make), arg0)
}
