// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: DevicesRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_devices_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests DevicesRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockDevicesRequestBody is a mock of DevicesRequestBody interface.
type MockDevicesRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockDevicesRequestBodyMockRecorder
	isgomock struct{}
}

// MockDevicesRequestBodyMockRecorder is the mock recorder for MockDevicesRequestBody.
type MockDevicesRequestBodyMockRecorder struct {
	mock *MockDevicesRequestBody
}

// NewMockDevicesRequestBody creates a new mock instance.
func NewMockDevicesRequestBody(ctrl *gomock.Controller) *MockDevicesRequestBody {
	mock := &MockDevicesRequestBody{ctrl: ctrl}
	mock.recorder = &MockDevicesRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevicesRequestBody) EXPECT() *MockDevicesRequestBodyMockRecorder {
	return m.recorder
}

// Make mocks base method.
func (m *MockDevicesRequestBody) Make(arg0 *gin.Context) requests.DevicesRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.DevicesRequestBody)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockDevicesRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockDevicesRequestBody)(nil).Make), arg0)
}
