// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LoginRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_login_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LoginRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginRequest is a mock of LoginRequest interface.
type MockLoginRequest struct {
	ctrl     *gomock.Controller
	recorder *MockLoginRequestMockRecorder
	isgomock struct{}
}

// MockLoginRequestMockRecorder is the mock recorder for MockLoginRequest.
type MockLoginRequestMockRecorder struct {
	mock *MockLoginRequest
}

// NewMockLoginRequest creates a new mock instance.
func NewMockLoginRequest(ctrl *gomock.Controller) *MockLoginRequest {
	mock := &MockLoginRequest{ctrl: ctrl}
	mock.recorder = &MockLoginRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginRequest) EXPECT() *MockLoginRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockLoginRequest) GetBody() requests.LoginRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.LoginRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockLoginRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockLoginRequest)(nil).GetBody))
}

// GetIP mocks base method.
func (m *MockLoginRequest) GetIP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIP")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetIP indicates an expected call of GetIP.
func (mr *MockLoginRequestMockRecorder) GetIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIP", reflect.TypeOf((*MockLoginRequest)(nil).GetIP))
}

// GetUserAgent mocks base method.
func (m *MockLoginRequest) GetUserAgent() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserAgent indicates an expected call of GetUserAgent.
func (mr *MockLoginRequestMockRecorder) GetUserAgent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAgent", reflect.TypeOf((*MockLoginRequest)(nil).GetUserAgent))
}

// Make mocks base method.
func (m *MockLoginRequest) Make(arg0 *gin.Context) (requests.LoginRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LoginRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockLoginRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLoginRequest)(nil).Make), arg0)
}
