// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LoginRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_login_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LoginRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLoginRequestBody is a mock of LoginRequestBody interface.
type MockLoginRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockLoginRequestBodyMockRecorder
	isgomock struct{}
}

// MockLoginRequestBodyMockRecorder is the mock recorder for MockLoginRequestBody.
type MockLoginRequestBodyMockRecorder struct {
	mock *MockLoginRequestBody
}

// NewMockLoginRequestBody creates a new mock instance.
func NewMockLoginRequestBody(ctrl *gomock.Controller) *MockLoginRequestBody {
	mock := &MockLoginRequestBody{ctrl: ctrl}
	mock.recorder = &MockLoginRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginRequestBody) EXPECT() *MockLoginRequestBodyMockRecorder {
	return m.recorder
}

// GetEmail mocks base method.
func (m *MockLoginRequestBody) GetEmail() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmail")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEmail indicates an expected call of GetEmail.
func (mr *MockLoginRequestBodyMockRecorder) GetEmail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmail", reflect.TypeOf((*MockLoginRequestBody)(nil).GetEmail))
}

// GetPassword mocks base method.
func (m *MockLoginRequestBody) GetPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockLoginRequestBodyMockRecorder) GetPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockLoginRequestBody)(nil).GetPassword))
}

// Make mocks base method.
func (m *MockLoginRequestBody) Make(arg0 *gin.Context) (requests.LoginRequestBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LoginRequestBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockLoginRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLoginRequestBody)(nil).Make), arg0)
}
