// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LogoutAllRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_logout_all_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LogoutAllRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutAllRequest is a mock of LogoutAllRequest interface.
type MockLogoutAllRequest struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutAllRequestMockRecorder
	isgomock struct{}
}

// MockLogoutAllRequestMockRecorder is the mock recorder for MockLogoutAllRequest.
type MockLogoutAllRequestMockRecorder struct {
	mock *MockLogoutAllRequest
}

// NewMockLogoutAllRequest creates a new mock instance.
func NewMockLogoutAllRequest(ctrl *gomock.Controller) *MockLogoutAllRequest {
	mock := &MockLogoutAllRequest{ctrl: ctrl}
	mock.recorder = &MockLogoutAllRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutAllRequest) EXPECT() *MockLogoutAllRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockLogoutAllRequest) GetBody() requests.LogoutAllRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.LogoutAllRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockLogoutAllRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockLogoutAllRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockLogoutAllRequest) Make(arg0 *gin.Context) requests.LogoutAllRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LogoutAllRequest)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockLogoutAllRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLogoutAllRequest)(nil).Make), arg0)
}
