// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: SendResetTokenRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_send_reset_token_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests SendResetTokenRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockSendResetTokenRequest is a mock of SendResetTokenRequest interface.
type MockSendResetTokenRequest struct {
	ctrl     *gomock.Controller
	recorder *MockSendResetTokenRequestMockRecorder
	isgomock struct{}
}

// MockSendResetTokenRequestMockRecorder is the mock recorder for MockSendResetTokenRequest.
type MockSendResetTokenRequestMockRecorder struct {
	mock *MockSendResetTokenRequest
}

// NewMockSendResetTokenRequest creates a new mock instance.
func NewMockSendResetTokenRequest(ctrl *gomock.Controller) *MockSendResetTokenRequest {
	mock := &MockSendResetTokenRequest{ctrl: ctrl}
	mock.recorder = &MockSendResetTokenRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendResetTokenRequest) EXPECT() *MockSendResetTokenRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockSendResetTokenRequest) GetBody() requests.SendResetTokenRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.SendResetTokenRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockSendResetTokenRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockSendResetTokenRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockSendResetTokenRequest) Make(arg0 *gin.Context) (requests.SendResetTokenRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.SendResetTokenRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockSendResetTokenRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockSendResetTokenRequest)(nil).Make), arg0)
}
