// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: SendResetTokenRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_send_reset_token_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests SendResetTokenRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockSendResetTokenRequestBody is a mock of SendResetTokenRequestBody interface.
type MockSendResetTokenRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockSendResetTokenRequestBodyMockRecorder
	isgomock struct{}
}

// MockSendResetTokenRequestBodyMockRecorder is the mock recorder for MockSendResetTokenRequestBody.
type MockSendResetTokenRequestBodyMockRecorder struct {
	mock *MockSendResetTokenRequestBody
}

// NewMockSendResetTokenRequestBody creates a new mock instance.
func NewMockSendResetTokenRequestBody(ctrl *gomock.Controller) *MockSendResetTokenRequestBody {
	mock := &MockSendResetTokenRequestBody{ctrl: ctrl}
	mock.recorder = &MockSendResetTokenRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendResetTokenRequestBody) EXPECT() *MockSendResetTokenRequestBodyMockRecorder {
	return m.recorder
}

// GetEmail mocks base method.
func (m *MockSendResetTokenRequestBody) GetEmail() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmail")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEmail indicates an expected call of GetEmail.
func (mr *MockSendResetTokenRequestBodyMockRecorder) GetEmail() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmail", reflect.TypeOf((*MockSendResetTokenRequestBody)(nil).GetEmail))
}

// Make mocks base method.
func (m *MockSendResetTokenRequestBody) Make(arg0 *gin.Context) (requests.SendResetTokenRequestBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.SendResetTokenRequestBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockSendResetTokenRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockSendResetTokenRequestBody)(nil).Make), arg0)
}
