// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: PasswordResetWithOldRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_password_reset_with_old_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests PasswordResetWithOldRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetWithOldRequest is a mock of PasswordResetWithOldRequest interface.
type MockPasswordResetWithOldRequest struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetWithOldRequestMockRecorder
	isgomock struct{}
}

// MockPasswordResetWithOldRequestMockRecorder is the mock recorder for MockPasswordResetWithOldRequest.
type MockPasswordResetWithOldRequestMockRecorder struct {
	mock *MockPasswordResetWithOldRequest
}

// NewMockPasswordResetWithOldRequest creates a new mock instance.
func NewMockPasswordResetWithOldRequest(ctrl *gomock.Controller) *MockPasswordResetWithOldRequest {
	mock := &MockPasswordResetWithOldRequest{ctrl: ctrl}
	mock.recorder = &MockPasswordResetWithOldRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetWithOldRequest) EXPECT() *MockPasswordResetWithOldRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockPasswordResetWithOldRequest) GetBody() requests.PasswordResetWithOldRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.PasswordResetWithOldRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockPasswordResetWithOldRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockPasswordResetWithOldRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockPasswordResetWithOldRequest) Make(arg0 *gin.Context) (requests.PasswordResetWithOldRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.PasswordResetWithOldRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockPasswordResetWithOldRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockPasswordResetWithOldRequest)(nil).Make), arg0)
}
