// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: RefreshRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_refresh_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests RefreshRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRefreshRequestBody is a mock of RefreshRequestBody interface.
type MockRefreshRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshRequestBodyMockRecorder
	isgomock struct{}
}

// MockRefreshRequestBodyMockRecorder is the mock recorder for MockRefreshRequestBody.
type MockRefreshRequestBodyMockRecorder struct {
	mock *MockRefreshRequestBody
}

// NewMockRefreshRequestBody creates a new mock instance.
func NewMockRefreshRequestBody(ctrl *gomock.Controller) *MockRefreshRequestBody {
	mock := &MockRefreshRequestBody{ctrl: ctrl}
	mock.recorder = &MockRefreshRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshRequestBody) EXPECT() *MockRefreshRequestBodyMockRecorder {
	return m.recorder
}

// GetRefreshToken mocks base method.
func (m *MockRefreshRequestBody) GetRefreshToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRefreshToken indicates an expected call of GetRefreshToken.
func (mr *MockRefreshRequestBodyMockRecorder) GetRefreshToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshToken", reflect.TypeOf((*MockRefreshRequestBody)(nil).GetRefreshToken))
}

// Make mocks base method.
func (m *MockRefreshRequestBody) Make(arg0 *gin.Context) (requests.RefreshRequestBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.RefreshRequestBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockRefreshRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockRefreshRequestBody)(nil).Make), arg0)
}
