// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LogoutDeviceRequestBody)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_logout_device_request_body.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LogoutDeviceRequestBody
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutDeviceRequestBody is a mock of LogoutDeviceRequestBody interface.
type MockLogoutDeviceRequestBody struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutDeviceRequestBodyMockRecorder
	isgomock struct{}
}

// MockLogoutDeviceRequestBodyMockRecorder is the mock recorder for MockLogoutDeviceRequestBody.
type MockLogoutDeviceRequestBodyMockRecorder struct {
	mock *MockLogoutDeviceRequestBody
}

// NewMockLogoutDeviceRequestBody creates a new mock instance.
func NewMockLogoutDeviceRequestBody(ctrl *gomock.Controller) *MockLogoutDeviceRequestBody {
	mock := &MockLogoutDeviceRequestBody{ctrl: ctrl}
	mock.recorder = &MockLogoutDeviceRequestBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutDeviceRequestBody) EXPECT() *MockLogoutDeviceRequestBodyMockRecorder {
	return m.recorder
}

// GetDeviceUUID mocks base method.
func (m *MockLogoutDeviceRequestBody) GetDeviceUUID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceUUID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDeviceUUID indicates an expected call of GetDeviceUUID.
func (mr *MockLogoutDeviceRequestBodyMockRecorder) GetDeviceUUID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceUUID", reflect.TypeOf((*MockLogoutDeviceRequestBody)(nil).GetDeviceUUID))
}

// Make mocks base method.
func (m *MockLogoutDeviceRequestBody) Make(arg0 *gin.Context) (requests.LogoutDeviceRequestBody, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LogoutDeviceRequestBody)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockLogoutDeviceRequestBodyMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLogoutDeviceRequestBody)(nil).Make), arg0)
}
