// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: BearerAuthRequestHeader)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_bearer_auth_request_header.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests BearerAuthRequestHeader
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	tokens "github.com/fromsi/jwt-oauth-sso/internal/tokens"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockBearerAuthRequestHeader is a mock of BearerAuthRequestHeader interface.
type MockBearerAuthRequestHeader struct {
	ctrl     *gomock.Controller
	recorder *MockBearerAuthRequestHeaderMockRecorder
	isgomock struct{}
}

// MockBearerAuthRequestHeaderMockRecorder is the mock recorder for MockBearerAuthRequestHeader.
type MockBearerAuthRequestHeaderMockRecorder struct {
	mock *MockBearerAuthRequestHeader
}

// NewMockBearerAuthRequestHeader creates a new mock instance.
func NewMockBearerAuthRequestHeader(ctrl *gomock.Controller) *MockBearerAuthRequestHeader {
	mock := &MockBearerAuthRequestHeader{ctrl: ctrl}
	mock.recorder = &MockBearerAuthRequestHeaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBearerAuthRequestHeader) EXPECT() *MockBearerAuthRequestHeaderMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockBearerAuthRequestHeader) GetAccessToken() tokens.AccessToken {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(tokens.AccessToken)
	return ret0
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockBearerAuthRequestHeaderMockRecorder) GetAccessToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockBearerAuthRequestHeader)(nil).GetAccessToken))
}

// Make mocks base method.
func (m *MockBearerAuthRequestHeader) Make(arg0 *gin.Context) (requests.BearerAuthRequestHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.BearerAuthRequestHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockBearerAuthRequestHeaderMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockBearerAuthRequestHeader)(nil).Make), arg0)
}
