// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: PasswordResetWithTokenRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_password_reset_with_token_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests PasswordResetWithTokenRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPasswordResetWithTokenRequest is a mock of PasswordResetWithTokenRequest interface.
type MockPasswordResetWithTokenRequest struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordResetWithTokenRequestMockRecorder
	isgomock struct{}
}

// MockPasswordResetWithTokenRequestMockRecorder is the mock recorder for MockPasswordResetWithTokenRequest.
type MockPasswordResetWithTokenRequestMockRecorder struct {
	mock *MockPasswordResetWithTokenRequest
}

// NewMockPasswordResetWithTokenRequest creates a new mock instance.
func NewMockPasswordResetWithTokenRequest(ctrl *gomock.Controller) *MockPasswordResetWithTokenRequest {
	mock := &MockPasswordResetWithTokenRequest{ctrl: ctrl}
	mock.recorder = &MockPasswordResetWithTokenRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordResetWithTokenRequest) EXPECT() *MockPasswordResetWithTokenRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockPasswordResetWithTokenRequest) GetBody() requests.PasswordResetWithTokenRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.PasswordResetWithTokenRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockPasswordResetWithTokenRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockPasswordResetWithTokenRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockPasswordResetWithTokenRequest) Make(arg0 *gin.Context) (requests.PasswordResetWithTokenRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.PasswordResetWithTokenRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockPasswordResetWithTokenRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockPasswordResetWithTokenRequest)(nil).Make), arg0)
}
