// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/requests (interfaces: LogoutRequest)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/requests/mock_logout_request.go -package=requests_mocks github.com/fromsi/jwt-oauth-sso/internal/http/requests LogoutRequest
//

// Package requests_mocks is a generated GoMock package.
package requests_mocks

import (
	reflect "reflect"

	requests "github.com/fromsi/jwt-oauth-sso/internal/http/requests"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockLogoutRequest is a mock of LogoutRequest interface.
type MockLogoutRequest struct {
	ctrl     *gomock.Controller
	recorder *MockLogoutRequestMockRecorder
	isgomock struct{}
}

// MockLogoutRequestMockRecorder is the mock recorder for MockLogoutRequest.
type MockLogoutRequestMockRecorder struct {
	mock *MockLogoutRequest
}

// NewMockLogoutRequest creates a new mock instance.
func NewMockLogoutRequest(ctrl *gomock.Controller) *MockLogoutRequest {
	mock := &MockLogoutRequest{ctrl: ctrl}
	mock.recorder = &MockLogoutRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogoutRequest) EXPECT() *MockLogoutRequestMockRecorder {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockLogoutRequest) GetBody() requests.LogoutRequestBody {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(requests.LogoutRequestBody)
	return ret0
}

// GetBody indicates an expected call of GetBody.
func (mr *MockLogoutRequestMockRecorder) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockLogoutRequest)(nil).GetBody))
}

// Make mocks base method.
func (m *MockLogoutRequest) Make(arg0 *gin.Context) requests.LogoutRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(requests.LogoutRequest)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockLogoutRequestMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockLogoutRequest)(nil).Make), arg0)
}
