// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/responses (interfaces: ErrorInternalServerResponse)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/responses/mock_error_internal_server_response.go -package=responses_mocks github.com/fromsi/jwt-oauth-sso/internal/http/responses ErrorInternalServerResponse
//

// Package responses_mocks is a generated GoMock package.
package responses_mocks

import (
	reflect "reflect"

	responses "github.com/fromsi/jwt-oauth-sso/internal/http/responses"
	gomock "go.uber.org/mock/gomock"
)

// MockErrorInternalServerResponse is a mock of ErrorInternalServerResponse interface.
type MockErrorInternalServerResponse struct {
	ctrl     *gomock.Controller
	recorder *MockErrorInternalServerResponseMockRecorder
	isgomock struct{}
}

// MockErrorInternalServerResponseMockRecorder is the mock recorder for MockErrorInternalServerResponse.
type MockErrorInternalServerResponseMockRecorder struct {
	mock *MockErrorInternalServerResponse
}

// NewMockErrorInternalServerResponse creates a new mock instance.
func NewMockErrorInternalServerResponse(ctrl *gomock.Controller) *MockErrorInternalServerResponse {
	mock := &MockErrorInternalServerResponse{ctrl: ctrl}
	mock.recorder = &MockErrorInternalServerResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorInternalServerResponse) EXPECT() *MockErrorInternalServerResponseMockRecorder {
	return m.recorder
}

// Make mocks base method.
func (m *MockErrorInternalServerResponse) Make(arg0 error) responses.ErrorInternalServerResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(responses.ErrorInternalServerResponse)
	return ret0
}

// Make indicates an expected call of Make.
func (mr *MockErrorInternalServerResponseMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockErrorInternalServerResponse)(nil).Make), arg0)
}
