// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/http/responses (interfaces: SuccessLoginResponse)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/http/responses/mock_success_login_response.go -package=responses_mocks github.com/fromsi/jwt-oauth-sso/internal/http/responses SuccessLoginResponse
//

// Package responses_mocks is a generated GoMock package.
package responses_mocks

import (
	reflect "reflect"

	responses "github.com/fromsi/jwt-oauth-sso/internal/http/responses"
	repositories "github.com/fromsi/jwt-oauth-sso/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockSuccessLoginResponse is a mock of SuccessLoginResponse interface.
type MockSuccessLoginResponse struct {
	ctrl     *gomock.Controller
	recorder *MockSuccessLoginResponseMockRecorder
	isgomock struct{}
}

// MockSuccessLoginResponseMockRecorder is the mock recorder for MockSuccessLoginResponse.
type MockSuccessLoginResponseMockRecorder struct {
	mock *MockSuccessLoginResponse
}

// NewMockSuccessLoginResponse creates a new mock instance.
func NewMockSuccessLoginResponse(ctrl *gomock.Controller) *MockSuccessLoginResponse {
	mock := &MockSuccessLoginResponse{ctrl: ctrl}
	mock.recorder = &MockSuccessLoginResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccessLoginResponse) EXPECT() *MockSuccessLoginResponseMockRecorder {
	return m.recorder
}

// Make mocks base method.
func (m *MockSuccessLoginResponse) Make(arg0 repositories.Device) (responses.SuccessLoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", arg0)
	ret0, _ := ret[0].(responses.SuccessLoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockSuccessLoginResponseMockRecorder) Make(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockSuccessLoginResponse)(nil).Make), arg0)
}
