// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/repositories (interfaces: MutableResetTokenRepository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/repositories/mock_mutable_reset_token_repository.go -package=repositories_mocks github.com/fromsi/jwt-oauth-sso/internal/repositories MutableResetTokenRepository
//

// Package repositories_mocks is a generated GoMock package.
package repositories_mocks

import (
	reflect "reflect"

	repositories "github.com/fromsi/jwt-oauth-sso/internal/repositories"
	gomock "go.uber.org/mock/gomock"
)

// MockMutableResetTokenRepository is a mock of MutableResetTokenRepository interface.
type MockMutableResetTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMutableResetTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockMutableResetTokenRepositoryMockRecorder is the mock recorder for MockMutableResetTokenRepository.
type MockMutableResetTokenRepositoryMockRecorder struct {
	mock *MockMutableResetTokenRepository
}

// NewMockMutableResetTokenRepository creates a new mock instance.
func NewMockMutableResetTokenRepository(ctrl *gomock.Controller) *MockMutableResetTokenRepository {
	mock := &MockMutableResetTokenRepository{ctrl: ctrl}
	mock.recorder = &MockMutableResetTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableResetTokenRepository) EXPECT() *MockMutableResetTokenRepositoryMockRecorder {
	return m.recorder
}

// CreateResetToken mocks base method.
func (m *MockMutableResetTokenRepository) CreateResetToken(arg0 repositories.ResetToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResetToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateResetToken indicates an expected call of CreateResetToken.
func (mr *MockMutableResetTokenRepositoryMockRecorder) CreateResetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResetToken", reflect.TypeOf((*MockMutableResetTokenRepository)(nil).CreateResetToken), arg0)
}

// DeleteResetToken mocks base method.
func (m *MockMutableResetTokenRepository) DeleteResetToken(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResetToken", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResetToken indicates an expected call of DeleteResetToken.
func (mr *MockMutableResetTokenRepositoryMockRecorder) DeleteResetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResetToken", reflect.TypeOf((*MockMutableResetTokenRepository)(nil).DeleteResetToken), arg0)
}
