// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: MutableUserService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/services/mock_mutable_user_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services MutableUserService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	gomock "go.uber.org/mock/gomock"
)

// MockMutableUserService is a mock of MutableUserService interface.
type MockMutableUserService struct {
	ctrl     *gomock.Controller
	recorder *MockMutableUserServiceMockRecorder
	isgomock struct{}
}

// MockMutableUserServiceMockRecorder is the mock recorder for MockMutableUserService.
type MockMutableUserServiceMockRecorder struct {
	mock *MockMutableUserService
}

// NewMockMutableUserService creates a new mock instance.
func NewMockMutableUserService(ctrl *gomock.Controller) *MockMutableUserService {
	mock := &MockMutableUserService{ctrl: ctrl}
	mock.recorder = &MockMutableUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableUserService) EXPECT() *MockMutableUserServiceMockRecorder {
	return m.recorder
}
