// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: ResetTokenService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/services/mock_reset_token_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services ResetTokenService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockResetTokenService is a mock of ResetTokenService interface.
type MockResetTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockResetTokenServiceMockRecorder
	isgomock struct{}
}

// MockResetTokenServiceMockRecorder is the mock recorder for MockResetTokenService.
type MockResetTokenServiceMockRecorder struct {
	mock *MockResetTokenService
}

// NewMockResetTokenService creates a new mock instance.
func NewMockResetTokenService(ctrl *gomock.Controller) *MockResetTokenService {
	mock := &MockResetTokenService{ctrl: ctrl}
	mock.recorder = &MockResetTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResetTokenService) EXPECT() *MockResetTokenServiceMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockResetTokenService) GenerateToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockResetTokenServiceMockRecorder) GenerateToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockResetTokenService)(nil).GenerateToken))
}

// ResetPasswordByUserUUIDAndNewPassword mocks base method.
func (m *MockResetTokenService) ResetPasswordByUserUUIDAndNewPassword(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordByUserUUIDAndNewPassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPasswordByUserUUIDAndNewPassword indicates an expected call of ResetPasswordByUserUUIDAndNewPassword.
func (mr *MockResetTokenServiceMockRecorder) ResetPasswordByUserUUIDAndNewPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordByUserUUIDAndNewPassword", reflect.TypeOf((*MockResetTokenService)(nil).ResetPasswordByUserUUIDAndNewPassword), arg0, arg1)
}

// ResetPasswordByUserUUIDAndOldPasswordAndNewPassword mocks base method.
func (m *MockResetTokenService) ResetPasswordByUserUUIDAndOldPasswordAndNewPassword(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordByUserUUIDAndOldPasswordAndNewPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPasswordByUserUUIDAndOldPasswordAndNewPassword indicates an expected call of ResetPasswordByUserUUIDAndOldPasswordAndNewPassword.
func (mr *MockResetTokenServiceMockRecorder) ResetPasswordByUserUUIDAndOldPasswordAndNewPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordByUserUUIDAndOldPasswordAndNewPassword", reflect.TypeOf((*MockResetTokenService)(nil).ResetPasswordByUserUUIDAndOldPasswordAndNewPassword), arg0, arg1, arg2)
}

// SendNewResetTokenByUserEmail mocks base method.
func (m *MockResetTokenService) SendNewResetTokenByUserEmail(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNewResetTokenByUserEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNewResetTokenByUserEmail indicates an expected call of SendNewResetTokenByUserEmail.
func (mr *MockResetTokenServiceMockRecorder) SendNewResetTokenByUserEmail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNewResetTokenByUserEmail", reflect.TypeOf((*MockResetTokenService)(nil).SendNewResetTokenByUserEmail), arg0)
}
