// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fromsi/jwt-oauth-sso/internal/services (interfaces: MutableResetTokenService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/services/mock_mutable_reset_token_service.go -package=services_mocks github.com/fromsi/jwt-oauth-sso/internal/services MutableResetTokenService
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMutableResetTokenService is a mock of MutableResetTokenService interface.
type MockMutableResetTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockMutableResetTokenServiceMockRecorder
	isgomock struct{}
}

// MockMutableResetTokenServiceMockRecorder is the mock recorder for MockMutableResetTokenService.
type MockMutableResetTokenServiceMockRecorder struct {
	mock *MockMutableResetTokenService
}

// NewMockMutableResetTokenService creates a new mock instance.
func NewMockMutableResetTokenService(ctrl *gomock.Controller) *MockMutableResetTokenService {
	mock := &MockMutableResetTokenService{ctrl: ctrl}
	mock.recorder = &MockMutableResetTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutableResetTokenService) EXPECT() *MockMutableResetTokenServiceMockRecorder {
	return m.recorder
}

// ResetPasswordByTokenAndNewPassword mocks base method.
func (m *MockMutableResetTokenService) ResetPasswordByTokenAndNewPassword(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordByTokenAndNewPassword", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPasswordByTokenAndNewPassword indicates an expected call of ResetPasswordByTokenAndNewPassword.
func (mr *MockMutableResetTokenServiceMockRecorder) ResetPasswordByTokenAndNewPassword(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordByTokenAndNewPassword", reflect.TypeOf((*MockMutableResetTokenService)(nil).ResetPasswordByTokenAndNewPassword), arg0, arg1)
}

// ResetPasswordByUserUUIDAndOldPasswordAndNewPassword mocks base method.
func (m *MockMutableResetTokenService) ResetPasswordByUserUUIDAndOldPasswordAndNewPassword(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordByUserUUIDAndOldPasswordAndNewPassword", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPasswordByUserUUIDAndOldPasswordAndNewPassword indicates an expected call of ResetPasswordByUserUUIDAndOldPasswordAndNewPassword.
func (mr *MockMutableResetTokenServiceMockRecorder) ResetPasswordByUserUUIDAndOldPasswordAndNewPassword(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordByUserUUIDAndOldPasswordAndNewPassword", reflect.TypeOf((*MockMutableResetTokenService)(nil).ResetPasswordByUserUUIDAndOldPasswordAndNewPassword), arg0, arg1, arg2)
}
